/**
 * Java 侧边栏json数据
 */
export const javaJson =
   // {
//        text: "Java",
//        icon: "java",
//        prefix: "java/",
//        collapsable: true,
        //children: "structure",
//        children: [
            {
                text: "基础",
                icon: "java",
                prefix: "basis/",
                collapsable: true,
                children: [
                    "arraylist",
                    "basic-grammar",
                    "data-structure",
                    "exception",
                    "io-note",
                    "mysql-setting",
                    "oop",
                    "string",
                    "web-servlet-jsp",
                ]
            },
            "test",
            "java-log",
            "java-jsr303",
            "java-exception",
            "23-design-patterns",
            "jvm",
            "nacos-gateway-sentinel-sleuth",
            "nacos-note",
            "oss",
            "spring-cloud-alibaba-note-basis",
            "spring-cloud-alibaba-note-high-level",
            "swagger",
            "spring-cloud-core-components",
            "cloud-session",
            "cloud-lock-cache",
            "local-cloud-affairs-seata",
            "single-sign-on",
            "timed-task",
            "asynchronous",
            "mybatis-plus",
            "permission-management",
            "jmeter",
            "template-engine-thymeleaf",
            {
                text: "新特性",
                prefix: "new-features/",
                icon: "featured",
                collapsable: true,
                children: [
                    "java8-common-new-features",
                    "java8-tutorial-translate",
                    "java9",
                    "java10",
                    "java11",
                    "java12-13",
                    "java14-15",
                    "java16",
                ],
            },
    //    ],
  //  }
