
name: 部署文档

on:
  push:
    #tags:
    branches:
      - main
    paths-ignore:
      - img/**
      - README.md
      - LICENSE

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: 安装 Deps
        run: pnpm install --frozen-lockfile

      - name: 构建文档
        env:
          # BASE: /v2/
          # HOSTNAME: https://topsjf.github.io/
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run build:vite
          > docs/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # repository-name: topsjf/v2
          # 这是文档部署到的分支名称
          branch: page-main
          folder: docs/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

